# Generated by Django 6.1 on 2026-09-19 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationrequest',
            name='phone',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
